<script setup>
import { computed } from 'vue'
const props=defineProps({accounts:{type:Array,default:()=>[]},currencies:{type:Array,default:()=>[]},baseCurrencyCode:String,disabled:Boolean,minLines:{type:Number,default:2}})
const lines=defineModel('lines',{type:Array,required:true})
const types={asset:'الأصول',liability:'الالتزامات',equity:'حقوق الملكية',revenue:'الإيرادات',contra_revenue:'مقابلات الإيراد',expense:'المصاريف'}
const groups=computed(()=>Object.entries(types).map(([key,label])=>({key,label,items:props.accounts.filter(a=>a.type===key)})).filter(g=>g.items.length))
const baseAmount=(amount,rate)=>Number(amount||0)*Number(rate||1);const totalDebit=computed(()=>lines.value.reduce((s,l)=>s+baseAmount(l.foreign_debit,l.exchange_rate),0));const totalCredit=computed(()=>lines.value.reduce((s,l)=>s+baseAmount(l.foreign_credit,l.exchange_rate),0));const difference=computed(()=>totalDebit.value-totalCredit.value);const balanced=computed(()=>Math.abs(difference.value)<.01&&totalDebit.value>0)
function emptyLine(){return{account_id:'',foreign_debit:'',foreign_credit:'',currency_code:props.baseCurrencyCode,exchange_rate:1,description:'',details:false}}
function add(){lines.value=[...lines.value,emptyLine()]}
function remove(index){if(lines.value.length<=props.minLines)return;lines.value=lines.value.filter((_,i)=>i!==index)}
function debit(line){if(Number(line.foreign_debit)>0)line.foreign_credit=''}function credit(line){if(Number(line.foreign_credit)>0)line.foreign_debit=''}
function currencyChanged(line){const currency=props.currencies.find(c=>c.code===line.currency_code);line.exchange_rate=currency?.base?1:(currency?.rate||'')}
defineExpose({balanced,totalDebit,totalCredit,difference})
</script>
<template><section class="lines-editor"><header><div><strong>سطور القيد</strong><small>كل سطر يحتوي جهة واحدة فقط: مدين أو دائن.</small></div><button type="button" :disabled="disabled" @click="add"><i class="bi bi-plus-lg"></i> سطر جديد</button></header><div class="lines"><article v-for="(line,index) in lines" :key="index"><span class="number">{{index+1}}</span><label class="account"><span>الحساب</span><select v-model="line.account_id" class="form-select" required :disabled="disabled"><option value="">اختر حساباً</option><optgroup v-for="group in groups" :key="group.key" :label="group.label"><option v-for="account in group.items" :key="account.id" :value="account.id">{{account.code}} — {{account.name}}{{account.system?' 🔒':''}}</option></optgroup></select></label><label><span>مدين</span><input v-model="line.foreign_debit" type="number" step=".0001" min="0" class="form-control amount" placeholder="0.00" :disabled="disabled" @input="debit(line)"></label><label><span>دائن</span><input v-model="line.foreign_credit" type="number" step=".0001" min="0" class="form-control amount" placeholder="0.00" :disabled="disabled" @input="credit(line)"></label><button type="button" class="details" :class="{open:line.details}" :disabled="disabled" title="عملة أو وصف" @click="line.details=!line.details"><i class="bi bi-sliders"></i></button><button type="button" class="remove" :disabled="disabled||lines.length<=minLines" @click="remove(index)"><i class="bi bi-trash3"></i></button><div v-if="line.details" class="line-details"><label><span>العملة</span><select v-model="line.currency_code" class="form-select" :disabled="disabled" @change="currencyChanged(line)"><option v-for="currency in currencies" :key="currency.code" :value="currency.code">{{currency.code}} — {{currency.name}}</option></select></label><label><span>سعر الصرف إلى {{baseCurrencyCode}}</span><input v-model="line.exchange_rate" type="number" min=".000001" step=".000001" class="form-control" :disabled="disabled||line.currency_code===baseCurrencyCode"></label><label class="description"><span>وصف السطر</span><input v-model="line.description" class="form-control" maxlength="255" :disabled="disabled"></label></div></article></div><footer><span><small>إجمالي مدين</small><strong>{{totalDebit.toFixed(2)}} {{baseCurrencyCode}}</strong></span><span><small>إجمالي دائن</small><strong>{{totalCredit.toFixed(2)}} {{baseCurrencyCode}}</strong></span><span class="state" :class="balanced?'ok':'bad'"><i class="bi" :class="balanced?'bi-check-circle-fill':'bi-exclamation-triangle-fill'"></i><strong>{{balanced?'القيد متوازن':`فرق ${Math.abs(difference).toFixed(2)} ${baseCurrencyCode}`}}</strong></span></footer></section></template>
<style scoped>.lines-editor{overflow:hidden;border:1px solid #dfe7e2;border-radius:16px;background:#fff}.lines-editor>header{display:flex;align-items:center;justify-content:space-between;padding:12px 14px;border-bottom:1px solid #edf1ee;background:#f8faf9}.lines-editor>header>div{display:grid}.lines-editor>header strong{font-size:.76rem}.lines-editor>header small{color:#7e8b83;font-size:.61rem}.lines-editor>header button{padding:7px 10px;border:1px solid #a6ccb2;border-radius:9px;color:#1f6b50;background:#fff;font-size:.63rem;font-weight:850}.lines{display:grid}.lines article{display:grid;grid-template-columns:28px minmax(220px,1.5fr) minmax(105px,.55fr) minmax(105px,.55fr) 34px 34px;align-items:end;gap:7px;padding:9px 12px;border-bottom:1px solid #edf1ee}.lines article>label,.line-details label{display:grid;gap:3px}.lines label>span{font-size:.58rem;font-weight:800}.number{display:grid;width:25px;height:25px;place-items:center;align-self:center;border-radius:8px;color:#1f6b50;background:#e9f4ed;font-size:.59rem;font-weight:900}.amount{text-align:end}.details,.remove{display:grid;width:33px;height:33px;place-items:center;border:1px solid #dfe7e2;border-radius:8px;color:#68776d;background:#fff}.details.open{color:#1f6b50;border-color:#a8ceb4;background:#f0f8f2}.remove{color:#ad3030}.line-details{display:grid;grid-column:2/-1;grid-template-columns:150px 170px 1fr;gap:8px;padding:8px;border-radius:10px;background:#f5f8f6}.lines-editor>footer{display:grid;grid-template-columns:160px 160px 1fr;align-items:center;gap:9px;padding:11px 14px;background:#f7faf8}.lines-editor>footer>span{display:grid}.lines-editor footer small{color:#7d8a82;font-size:.57rem}.lines-editor footer strong{font-size:.71rem}.state{display:flex!important;align-items:center;justify-content:flex-end;gap:6px}.state.ok{color:#1f6b50}.state.bad{color:#ad2929}@media(max-width:850px){.lines article{grid-template-columns:28px 1fr 1fr 34px}.lines .account{grid-column:2/-1}.lines .details{grid-column:3}.line-details{grid-column:2/-1;grid-template-columns:1fr 1fr}.line-details .description{grid-column:1/-1}}@media(max-width:520px){.lines article{grid-template-columns:24px 1fr 1fr}.lines .account{grid-column:2/-1}.lines .details{grid-column:2}.lines .remove{grid-column:3}.line-details{grid-column:1/-1}.lines-editor>footer{grid-template-columns:1fr 1fr}.state{grid-column:1/-1;justify-content:flex-start}.lines-editor>header small{display:none}}</style>
