<script setup>
import { reactive } from 'vue'
import { Head, router } from '@inertiajs/vue3'
import AdminLayout from '../../../Layouts/AdminLayout.vue'
import PageHeader from '../../../Components/Ui/PageHeader.vue'
import AccountingNav from '../../../Components/Accounting/AccountingNav.vue'
import AccountingPanel from '../../../Components/Accounting/AccountingPanel.vue'
defineOptions({layout:AdminLayout})
const props=defineProps({asOf:String,arRows:Array,apRows:Array,totals:Object,currency:Object,urls:Object})
const form=reactive({as_of:props.asOf});const money=(v)=>`${new Intl.NumberFormat('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(v||0))} ${props.currency.symbol}`;const visit=()=>router.get(props.urls.index,form,{preserveState:true,preserveScroll:true})
const buckets=[['current','حتى 30 يوماً'],['31_60','31–60 يوماً'],['61_90','61–90 يوماً'],['over_90','أكثر من 90']]
const bucketLabel=(key)=>buckets.find((item)=>item[0]===key)?.[1]||key
</script>
<template><Head title="أعمار الذمم"/><PageHeader title="أعمار الذمم" icon="bi-hourglass-split" subtitle="ما يجب تحصيله من الزبائن وما يجب سداده للموردين، مرتّباً حسب العمر"/><AccountingNav :urls="urls" active="aging"/>
<form class="filter" @submit.prevent="visit"><label><span>الأرصدة كما في</span><input v-model="form.as_of" type="date" class="form-control"></label><button class="btn btn-primary"><i class="bi bi-search"></i> تحديث</button></form>
<div class="aging-summary"><article class="receive"><span><i class="bi bi-person-down"></i></span><div><small>مطلوب من الزبائن</small><strong>{{money(totals.receivables.total)}}</strong><em>{{arRows.length}} فاتورة مفتوحة</em></div></article><article class="pay"><span><i class="bi bi-truck"></i></span><div><small>مطلوب للموردين</small><strong>{{money(totals.payables.total)}}</strong><em>{{apRows.length}} فاتورة مفتوحة</em></div></article></div>
<div class="aging-grid">
<AccountingPanel title="ذمم الزبائن" description="ابدأ بالأقدم عند متابعة التحصيل." icon="bi-person-lines-fill"><div class="bucket-strip"><span v-for="bucket in buckets" :key="bucket[0]"><small>{{bucket[1]}}</small><bdi>{{money(totals.receivables[bucket[0]])}}</bdi></span></div><div class="aging-list"><article v-for="row in arRows" :key="`${row.number}-${row.party}`"><div><strong>{{row.party}}</strong><small>{{row.number}} · {{row.date}}</small></div><span :data-age="row.bucket">{{bucketLabel(row.bucket)}}</span><bdi>{{money(row.amount)}}</bdi></article><p v-if="!arRows.length">لا توجد ذمم زبائن مفتوحة.</p></div><div class="tie" :class="{warn:Math.abs(totals.receivablesUnassigned)>.01}"><span><small>رصيد دفتر الأستاذ</small><strong>{{money(totals.receivablesLedger)}}</strong></span><span><small>فرق غير مربوط بفواتير</small><strong>{{money(totals.receivablesUnassigned)}}</strong></span></div></AccountingPanel>
<AccountingPanel title="ذمم الموردين" description="رتّب الدفع حسب الاستحقاق والسيولة." icon="bi-truck" tone="amber"><div class="bucket-strip"><span v-for="bucket in buckets" :key="bucket[0]"><small>{{bucket[1]}}</small><bdi>{{money(totals.payables[bucket[0]])}}</bdi></span></div><div class="aging-list"><article v-for="row in apRows" :key="`${row.number}-${row.party}`"><div><strong>{{row.party}}</strong><small>{{row.number}} · {{row.date}}</small></div><span :data-age="row.bucket">{{bucketLabel(row.bucket)}}</span><bdi>{{money(row.amount)}}</bdi></article><p v-if="!apRows.length">لا توجد ذمم موردين مفتوحة.</p></div><div class="tie" :class="{warn:Math.abs(totals.payablesUnassigned)>.01}"><span><small>رصيد دفتر الأستاذ</small><strong>{{money(totals.payablesLedger)}}</strong></span><span><small>فرق غير مربوط بفواتير</small><strong>{{money(totals.payablesUnassigned)}}</strong></span></div></AccountingPanel>
</div></template>
<style scoped>.filter{display:flex;align-items:end;gap:9px;margin-bottom:10px;padding:10px;border:1px solid #dfe7e2;border-radius:13px;background:#fff}.filter label{display:grid;gap:4px;width:240px}.filter label span{font-size:.64rem;font-weight:850}.aging-summary{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-bottom:11px}.aging-summary article{display:flex;align-items:center;gap:11px;padding:14px;border:1px solid #dfe7e2;border-radius:14px;background:#fff}.aging-summary article>span{display:grid;width:40px;height:40px;place-items:center;border-radius:11px;color:#1f6b50;background:#e8f3ec}.aging-summary article.pay>span{color:#a65b00;background:#fff0d9}.aging-summary article>div{display:grid}.aging-summary small{color:#7b897f;font-size:.64rem}.aging-summary strong{font-size:1rem}.aging-summary em{color:#8b978f;font-size:.59rem;font-style:normal}.aging-grid{display:grid;grid-template-columns:1fr 1fr;align-items:start;gap:11px}.bucket-strip{display:grid;grid-template-columns:repeat(4,1fr);gap:5px;margin-bottom:10px}.bucket-strip span{display:grid;gap:2px;padding:8px;border-radius:10px;background:#f5f8f6}.bucket-strip small{color:#7f8c84;font-size:.54rem}.bucket-strip bdi{font-size:.63rem;font-weight:850}.aging-list{display:grid}.aging-list article{display:grid;grid-template-columns:1fr auto auto;align-items:center;gap:8px;padding:9px 0;border-bottom:1px solid #edf1ee}.aging-list article>div{display:grid}.aging-list strong{font-size:.69rem}.aging-list small{color:#859188;font-size:.59rem}.aging-list article>span{padding:3px 7px;border-radius:999px;color:#536259;background:#eff3f0;font-size:.55rem;font-weight:800}.aging-list article>span[data-age="over_90"]{color:#ad2929;background:#fff0f0}.aging-list article>span[data-age="61_90"]{color:#a15a00;background:#fff1dd}.aging-list article>bdi{font-size:.67rem;font-weight:900}.aging-list p{margin:26px 0;color:#849188;font-size:.68rem;text-align:center}.tie{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:10px;padding:9px;border-radius:11px;background:#f4f7f5}.tie span{display:grid}.tie span+span{padding-inline-start:8px;border-inline-start:1px solid #dfe7e2}.tie small{color:#7d8a82;font-size:.56rem}.tie strong{font-size:.68rem}.tie.warn span:last-child strong{color:#ae3d24}@media(max-width:950px){.aging-grid{grid-template-columns:1fr}}@media(max-width:560px){.aging-summary{grid-template-columns:1fr}.filter{display:grid}.filter label{width:100%}.bucket-strip{grid-template-columns:repeat(2,1fr)}.aging-list article{grid-template-columns:1fr auto}.aging-list article>span{grid-column:1}.aging-list article>bdi{grid-column:2;grid-row:1/3}}</style>
