<script setup>
import { computed } from 'vue'
import { Head, useForm } from '@inertiajs/vue3'
import AdminLayout from '../../../Layouts/AdminLayout.vue'
import PageHeader from '../../../Components/Ui/PageHeader.vue'
import AccountingNav from '../../../Components/Accounting/AccountingNav.vue'
import AccountingPanel from '../../../Components/Accounting/AccountingPanel.vue'
import JournalLinesEditor from '../../../Components/Accounting/JournalLinesEditor.vue'
defineOptions({layout:AdminLayout})
const props=defineProps({entry:Object,accounts:Array,isReversed:Boolean,currencies:Array,baseCurrencyCode:String,urls:Object});const today=new Date().toISOString().slice(0,10);const form=useForm({mode:'reverse',posted_on:today,reason:'',correction_description:`تصحيح قيد ${props.entry.number}`,lines:props.entry.lines.map(l=>({account_id:l.accountId,description:l.description||'',foreign_debit:l.foreignDebit||'',foreign_credit:l.foreignCredit||'',currency_code:l.currencyCode,exchange_rate:l.exchangeRate,details:l.currencyCode!==props.baseCurrencyCode||Boolean(l.description)}))});const debit=computed(()=>form.lines.reduce((s,l)=>s+Number(l.foreign_debit||0)*Number(l.exchange_rate||1),0));const credit=computed(()=>form.lines.reduce((s,l)=>s+Number(l.foreign_credit||0)*Number(l.exchange_rate||1),0));const ready=computed(()=>!props.isReversed&&form.reason.trim()&&(form.mode==='reverse'||(Math.abs(debit.value-credit.value)<.01&&debit.value>0)));const money=v=>new Intl.NumberFormat('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(v||0));const submit=()=>form.post(props.urls.store)
</script>
<template><Head title="عكس أو تصحيح قيد"/><PageHeader title="عكس أو تصحيح قيد" icon="bi-arrow-counterclockwise" subtitle="التاريخ يبقى محفوظاً: نعكس الخطأ ثم نرحّل الصورة الصحيحة"/><AccountingNav :urls="urls" active="journal"/><section v-if="isReversed" class="reversed"><i class="bi bi-shield-exclamation"></i><div><strong>هذا القيد عُكس سابقاً</strong><small>لا يمكن عكس القيد نفسه مرتين. ارجع لدفتر القيود لمراجعة العكس والتصحيح.</small></div></section><div class="adjust-layout"><AccountingPanel title="القيد الأصلي" :description="`${entry.number} · ${entry.date}`" icon="bi-journal-text"><dl><div><dt>الوصف</dt><dd>{{entry.description}}</dd></div><div><dt>الفرع</dt><dd>{{entry.branch}}</dd></div></dl><div class="original-lines"><article v-for="(line,i) in entry.lines" :key="i"><span><bdi>{{line.accountCode}}</bdi><strong>{{line.accountName}}</strong></span><bdi v-if="line.debit">مدين {{money(line.debit)}}</bdi><bdi v-else>دائن {{money(line.credit)}}</bdi></article></div></AccountingPanel><main><section class="choice"><button type="button" :class="{active:form.mode==='reverse'}" :disabled="isReversed" @click="form.mode='reverse'"><i class="bi bi-arrow-counterclockwise"></i><span><strong>عكس فقط</strong><small>إلغاء أثر القيد الأصلي بالكامل</small></span></button><button type="button" :class="{active:form.mode==='correct'}" :disabled="isReversed" @click="form.mode='correct'"><i class="bi bi-wrench-adjustable"></i><span><strong>عكس ثم تصحيح</strong><small>إلغاء الأصل وترحيل قيد صحيح</small></span></button></section><form class="adjust-form" @submit.prevent="submit"><section class="details"><label><span>تاريخ التنفيذ *</span><input v-model="form.posted_on" type="date" class="form-control" required :disabled="isReversed"></label><label><span>سبب العكس أو التصحيح *</span><textarea v-model="form.reason" rows="2" class="form-control" placeholder="سبب واضح للمراجعة والتدقيق" required :disabled="isReversed"></textarea></label><label v-if="form.mode==='correct'"><span>وصف القيد المصحح *</span><input v-model="form.correction_description" class="form-control" required :disabled="isReversed"></label></section><JournalLinesEditor v-if="form.mode==='correct'" v-model:lines="form.lines" :accounts="accounts" :currencies="currencies" :base-currency-code="baseCurrencyCode" :disabled="isReversed"/><div class="impact"><i class="bi bi-info-circle"></i><span v-if="form.mode==='reverse'">سينشئ النظام قيداً معاكساً بنفس السطور والمبالغ، ولن يحذف الأصل.</span><span v-else>سينشئ النظام قيد عكس أولاً ثم قيداً جديداً بالسطور الصحيحة.</span></div><footer><a :href="urls.journal" class="btn btn-light">إلغاء</a><button class="btn btn-warning" :disabled="!ready||form.processing"><i class="bi bi-arrow-counterclockwise"></i> تنفيذ {{form.mode==='reverse'?'العكس':'التصحيح'}}</button></footer></form></main></div></template>
<style scoped>.reversed{display:flex;gap:9px;margin-bottom:11px;padding:12px 14px;border:1px solid #e2bd79;border-radius:13px;color:#925500;background:#fff6e6}.reversed div{display:grid}.reversed strong{font-size:.73rem}.reversed small{font-size:.62rem}.adjust-layout{display:grid;grid-template-columns:minmax(290px,.6fr) minmax(0,1.4fr);align-items:start;gap:11px}.adjust-layout>:first-child{position:sticky;top:183px}dl{display:grid;margin:0}dl div{display:flex;gap:8px;padding:7px 0;border-bottom:1px solid #edf1ee}dt{flex:0 0 65px;color:#7d8a82;font-size:.61rem}dd{margin:0;font-size:.65rem;font-weight:750}.original-lines{display:grid;margin-top:10px}.original-lines article{display:flex;align-items:center;gap:8px;padding:8px 0;border-bottom:1px solid #edf1ee}.original-lines article>span{display:flex;flex:1;align-items:center;gap:6px}.original-lines article>span bdi{color:#1f6b50;font-size:.62rem;font-weight:900}.original-lines article strong,.original-lines article>bdi{font-size:.63rem}.choice{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-bottom:9px}.choice button{display:flex;align-items:center;gap:9px;padding:11px;border:1px solid #dfe7e2;border-radius:13px;color:#536158;background:#fff;text-align:start}.choice button>i{display:grid;width:36px;height:36px;place-items:center;border-radius:10px;color:#915500;background:#fff0d9}.choice button span{display:grid}.choice strong{font-size:.7rem}.choice small{color:#829087;font-size:.58rem}.choice button.active{border-color:#dfbd79;background:#fff8eb;box-shadow:inset 0 -2px #b96b00}.adjust-form{display:grid;gap:9px}.details{display:grid;grid-template-columns:180px 1fr;gap:9px;padding:12px;border:1px solid #dfe7e2;border-radius:14px;background:#fff}.details label{display:grid;gap:4px}.details label>span{font-size:.62rem;font-weight:850}.details label:nth-child(2){grid-column:2}.details label:nth-child(3){grid-column:1/-1}.impact{display:flex;gap:7px;padding:9px 11px;border-radius:10px;color:#536158;background:#f3f6f4;font-size:.62rem}.adjust-form>footer{display:flex;justify-content:flex-end;gap:7px}@media(max-width:950px){.adjust-layout{grid-template-columns:1fr}.adjust-layout>:first-child{position:static}}@media(max-width:600px){.choice,.details{grid-template-columns:1fr}.details label:nth-child(2),.details label:nth-child(3){grid-column:auto}}</style>
