<script setup>
import { computed } from 'vue'
import { Head, useForm } from '@inertiajs/vue3'
import AdminLayout from '../../../Layouts/AdminLayout.vue'
import PageHeader from '../../../Components/Ui/PageHeader.vue'
import AccountingNav from '../../../Components/Accounting/AccountingNav.vue'
import JournalLinesEditor from '../../../Components/Accounting/JournalLinesEditor.vue'
import { localDateInput } from '../../../Utils/dateInput'
defineOptions({layout:AdminLayout})
const props=defineProps({accounts:Array,currencies:Array,baseCurrencyCode:String,urls:Object});const today=localDateInput();const line=()=>({account_id:'',foreign_debit:'',foreign_credit:'',currency_code:props.baseCurrencyCode,exchange_rate:1,description:'',details:false});const form=useForm({_idem:crypto.randomUUID(),posted_on:today,description:'',lines:[line(),line()]});const debit=computed(()=>form.lines.reduce((s,l)=>s+Number(l.foreign_debit||0)*Number(l.exchange_rate||1),0));const credit=computed(()=>form.lines.reduce((s,l)=>s+Number(l.foreign_credit||0)*Number(l.exchange_rate||1),0));const balanced=computed(()=>debit.value>0&&Math.abs(debit.value-credit.value)<.01&&form.lines.filter(l=>l.account_id).length>=2);const submit=()=>form.post(props.urls.store)
</script>
<template><Head title="قيد محاسبي يدوي"/><PageHeader title="قيد محاسبي يدوي" icon="bi-journal-plus" subtitle="لحركة لم يسجلها النظام تلقائياً فقط"/><AccountingNav :urls="urls" active="manualEntry"/><section class="manual-note"><i class="bi bi-lightning-charge-fill"></i><div><strong>لا تكرر العمليات اليومية هنا</strong><small>المبيعات والتحصيل والمخزون والموردون والمصاريف تسجل قيودها من شاشاتها. استخدم هذا القيد لتسوية أو حركة مستقلة يقررها المحاسب.</small></div><a :href="urls.guide">دليل الترحيل</a></section><form class="entry-form" @submit.prevent="submit"><section class="entry-head"><label><span>تاريخ القيد *</span><input v-model="form.posted_on" type="date" class="form-control" required></label><label><span>وصف واضح للقيد *</span><input v-model="form.description" class="form-control" maxlength="255" placeholder="مثال: تسوية فرق كشف البنك لشهر مايو" required></label></section><JournalLinesEditor v-model:lines="form.lines" :accounts="accounts" :currencies="currencies" :base-currency-code="baseCurrencyCode"/><div v-if="Object.keys(form.errors).length" class="errors"><i class="bi bi-exclamation-triangle"></i><div><strong>راجع بيانات القيد</strong><small v-for="(error,key) in form.errors" :key="key">{{error}}</small></div></div><footer><a :href="urls.journal" class="btn btn-light">إلغاء</a><button class="btn btn-primary" :disabled="!balanced||form.processing"><i class="bi bi-check2-circle"></i> ترحيل القيد</button></footer></form></template>
<style scoped>.manual-note{display:flex;align-items:center;gap:10px;margin-bottom:11px;padding:12px 14px;border:1px solid #b9d7e8;border-radius:13px;color:#1e6287;background:#f0f8fc}.manual-note>div{display:grid;flex:1}.manual-note strong{font-size:.73rem}.manual-note small{font-size:.62rem;line-height:1.55}.manual-note a{color:#176088;font-size:.63rem;font-weight:850}.entry-form{display:grid;gap:11px}.entry-head{display:grid;grid-template-columns:220px 1fr;gap:9px;padding:12px;border:1px solid #dfe7e2;border-radius:14px;background:#fff}.entry-head label{display:grid;gap:4px}.entry-head span{font-size:.63rem;font-weight:850}.entry-form>footer{display:flex;justify-content:flex-end;gap:7px}.errors{display:flex;gap:8px;padding:10px 12px;border-radius:10px;color:#ad2929;background:#fff0f0}.errors div{display:grid}.errors strong{font-size:.68rem}.errors small{font-size:.59rem}@media(max-width:620px){.manual-note{align-items:flex-start;flex-wrap:wrap}.manual-note a{width:100%;padding-inline-start:25px}.entry-head{grid-template-columns:1fr}}</style>
