<script setup>
import { reactive } from 'vue'
import { Head, router } from '@inertiajs/vue3'
import AdminLayout from '../../../Layouts/AdminLayout.vue'
import PageHeader from '../../../Components/Ui/PageHeader.vue'
import AccountingNav from '../../../Components/Accounting/AccountingNav.vue'
import AccountingPanel from '../../../Components/Accounting/AccountingPanel.vue'
defineOptions({layout:AdminLayout})
const props=defineProps({currency:Object,accounts:Array,filters:Object,metrics:Object,urls:Object})
const form=reactive({...props.filters})
function visit(){router.get(props.urls.index,{from:form.from||undefined,to:form.to||undefined,show_empty:form.showEmpty?1:0},{preserveState:true,preserveScroll:true})}
function money(v){return `${new Intl.NumberFormat('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(v||0))} ${props.currency.symbol}`}
</script>
<template>
<Head title="ميزان المراجعة"/><PageHeader title="ميزان المراجعة" icon="bi-columns-gap" subtitle="اختبار سريع أن مجموع الأرصدة المدينة يساوي الدائنة"/><AccountingNav :urls="urls" active="trialBalance"/>
<section class="balance-state" :class="metrics.balanced?'ok':'bad'"><span><i class="bi" :class="metrics.balanced?'bi-check2-circle':'bi-exclamation-triangle'"></i></span><div><strong>{{metrics.balanced?'الميزان متوازن':'يوجد فرق يحتاج مراجعة'}}</strong><small>{{metrics.balanced?'يمكن متابعة مراجعة الفترة بثقة.':'افتح دفتر القيود وحدد الحركة غير المتوازنة.'}}</small></div><bdi>{{money(Math.abs(metrics.balanceDebit-metrics.balanceCredit))}}</bdi></section>
<div class="metric-grid"><article><small>حسابات عليها حركة</small><strong>{{metrics.activeAccounts}}</strong><span v-if="metrics.hiddenZero">{{metrics.hiddenZero}} بلا حركة مخفية</span></article><article><small>إجمالي الرصيد المدين</small><strong>{{money(metrics.balanceDebit)}}</strong></article><article><small>إجمالي الرصيد الدائن</small><strong>{{money(metrics.balanceCredit)}}</strong></article></div>
<form class="period-filter" @submit.prevent="visit"><label><span>من</span><input v-model="form.from" type="date" class="form-control"></label><label><span>إلى</span><input v-model="form.to" type="date" class="form-control"></label><label class="switch"><input v-model="form.showEmpty" type="checkbox"><span><strong>إظهار الحسابات بلا حركة</strong><small>للمراجعة الشاملة فقط</small></span></label><button class="btn btn-primary"><i class="bi bi-search"></i> تحديث</button></form>
<AccountingPanel title="أرصدة الحسابات" :description="`${accounts.length} من أصل ${metrics.totalAccounts} حساباً`" icon="bi-columns-gap" compact>
<div class="trial-table"><div class="trial-head"><span>الحساب</span><span>حركة مدينة</span><span>حركة دائنة</span><span>رصيد مدين</span><span>رصيد دائن</span></div><a v-for="account in accounts" :key="account.id" :href="account.ledgerUrl" :class="{muted:account.zero}"><span><bdi>{{account.code}}</bdi><strong>{{account.name}}</strong><small v-if="!account.active">معطّل</small></span><bdi>{{money(account.movementDebit)}}</bdi><bdi>{{money(account.movementCredit)}}</bdi><bdi>{{money(account.balanceDebit)}}</bdi><bdi>{{money(account.balanceCredit)}}</bdi></a><div v-if="!accounts.length" class="empty"><i class="bi bi-inbox"></i><strong>لا توجد حركات في هذه الفترة</strong></div><div class="trial-total"><strong>المجموع</strong><bdi>{{money(metrics.movementDebit)}}</bdi><bdi>{{money(metrics.movementCredit)}}</bdi><bdi>{{money(metrics.balanceDebit)}}</bdi><bdi>{{money(metrics.balanceCredit)}}</bdi></div></div>
</AccountingPanel>
</template>
<style scoped>
.balance-state{display:flex;align-items:center;gap:11px;margin-bottom:10px;padding:12px 14px;border:1px solid;border-radius:14px}.balance-state.ok{color:#1f6b50;border-color:#a6d1b3;background:#f0f8f2}.balance-state.bad{color:#aa2828;border-color:#e9b8b8;background:#fff4f4}.balance-state>span{font-size:1.3rem}.balance-state>div{display:grid;flex:1}.balance-state strong{font-size:.8rem}.balance-state small{opacity:.75;font-size:.65rem}.balance-state>bdi{font-size:.78rem;font-weight:900}.metric-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:9px;margin-bottom:10px}.metric-grid article{display:grid;min-height:80px;align-content:center;padding:11px 13px;border:1px solid #dfe7e2;border-radius:13px;background:#fff}.metric-grid small{color:#7a887f;font-size:.65rem}.metric-grid strong{font-size:.93rem}.metric-grid span{color:#919c95;font-size:.61rem}.period-filter{display:grid;grid-template-columns:180px 180px 1fr auto;align-items:end;gap:9px;margin-bottom:10px;padding:11px;border:1px solid #dfe7e2;border-radius:13px;background:#fff}.period-filter>label:not(.switch){display:grid;gap:4px}.period-filter label>span{font-size:.66rem;font-weight:800}.switch{display:flex;align-items:center;gap:8px;padding-bottom:6px}.switch input{width:18px;height:18px;accent-color:#1f6b50}.switch>span{display:grid}.switch small{color:#829087;font-size:.6rem;font-weight:500}.trial-table{overflow-x:auto}.trial-head,.trial-table>a,.trial-total{display:grid;grid-template-columns:minmax(250px,1.5fr) repeat(4,minmax(115px,.7fr));align-items:center;gap:8px;min-width:790px;padding:9px 14px}.trial-head{color:#738178;background:#f7f9f7;font-size:.63rem;font-weight:850}.trial-head span:not(:first-child),.trial-table>a>bdi,.trial-total bdi{text-align:end}.trial-table>a{border-bottom:1px solid #edf1ee;color:#35463b;font-size:.68rem}.trial-table>a:hover{background:#f8fbf9}.trial-table>a.muted{opacity:.6}.trial-table>a>span{display:flex;align-items:center;gap:7px}.trial-table>a>span bdi{color:#1f6b50;font-weight:900}.trial-table>a>span strong{font-size:.7rem}.trial-table>a>span small{padding:2px 5px;border-radius:999px;color:#9d5900;background:#fff0d9;font-size:.55rem}.trial-table>a>bdi{font-weight:750}.trial-total{background:#f2f7f4;font-size:.7rem;font-weight:900}.empty{display:grid;min-width:790px;justify-items:center;gap:5px;padding:45px;color:#829087}.empty i{font-size:1.5rem}
@media(max-width:720px){.metric-grid{grid-template-columns:1fr}.period-filter{grid-template-columns:1fr 1fr}.period-filter .switch{grid-column:1/-1}}
@media(max-width:480px){.period-filter{grid-template-columns:1fr}.period-filter .switch{grid-column:auto}.balance-state>bdi{display:none}}
</style>
