<script setup>
import { computed } from 'vue';
import { Head, useForm } from '@inertiajs/vue3';
import AdminLayout from '../../../Layouts/AdminLayout.vue';
import PageHeader from '../../../Components/Ui/PageHeader.vue';

defineOptions({ layout: AdminLayout });
const props = defineProps({ table:{type:Object,required:true}, zones:{type:Array,default:()=>[]}, canManageZones:Boolean, urls:{type:Object,required:true} });
const editing = computed(() => Boolean(props.table.id));
const form = useForm({ number:props.table.number, name:props.table.name, capacity:props.table.capacity, zone_lookup_id:props.table.zoneId??'', status:props.table.status, active:Boolean(props.table.active) });
const statusOptions=[{value:'available',label:'متاحة للخدمة',icon:'bi-check-circle',help:'تظهر للجرسون ويمكن فتح طلب عليها'},{value:'reserved',label:'محجوزة',icon:'bi-calendar-check',help:'محجوزة لضيف أو موعد قريب'},{value:'out_of_service',label:'خارج الخدمة',icon:'bi-tools',help:'تنظيف أو صيانة ولا تستقبل طلباً'},{value:'occupied',label:'مشغولة',icon:'bi-people',help:'استخدمها فقط عند تصحيح حالة فعلية'}];
function submit(){editing.value?form.put(props.urls.submit,{preserveScroll:true}):form.post(props.urls.submit,{preserveScroll:true})}
</script>
<template>
<Head :title="editing?`تعديل طاولة ${table.number}`:'طاولة جديدة'"/>
<PageHeader :title="editing?`تعديل طاولة ${table.number}`:'إضافة طاولة'" icon="bi-grid-3x3-gap-fill" subtitle="بيانات قليلة تكفي لتظهر الطاولة فوراً في لوحة الصالة" :crumbs="[{label:'لوحة الصالة',url:urls.index}]"/>
<form class="table-form" @submit.prevent="submit">
  <section class="card main-card"><header><div><small>تعريف الطاولة</small><h2>ما الذي يراه الجرسون؟</h2></div><span class="preview-number">{{form.number||'—'}}</span></header>
    <div class="fields"><label><span>رقم الطاولة *</span><input v-model="form.number" class="form-control number" maxlength="16" required autofocus placeholder="مثال: 12"><small>يمكن تكرار الرقم في فرع آخر.</small><em v-if="form.errors.number">{{form.errors.number}}</em></label><label><span>اسم إضافي</span><input v-model="form.name" class="form-control" maxlength="255" placeholder="مثال: قرب النافذة"><em v-if="form.errors.name">{{form.errors.name}}</em></label><label><span>السعة *</span><div class="capacity"><button type="button" @click="form.capacity=Math.max(1,Number(form.capacity)-1)">−</button><input v-model="form.capacity" type="number" min="1" max="50" required><button type="button" @click="form.capacity=Math.min(50,Number(form.capacity)+1)">+</button></div><em v-if="form.errors.capacity">{{form.errors.capacity}}</em></label><label><span>القسم</span><select v-model="form.zone_lookup_id" class="form-select"><option value="">بدون قسم</option><option v-for="zone in zones" :key="zone.id" :value="zone.id">{{zone.label}}</option></select><a v-if="canManageZones" :href="urls.zones">إدارة أقسام الصالة</a><em v-if="form.errors.zone_lookup_id">{{form.errors.zone_lookup_id}}</em></label></div>
  </section>
  <section class="card"><header class="section-head"><div><small>الحالة</small><h2>هل تستقبل طلباً الآن؟</h2></div><label class="active-switch"><input v-model="form.active" type="checkbox"><span></span><b>{{form.active?'نشطة':'مخفية'}}</b></label></header><div class="status-grid"><button v-for="status in statusOptions" :key="status.value" type="button" :class="{selected:form.status===status.value}" @click="form.status=status.value"><i class="bi" :class="status.icon"></i><span><strong>{{status.label}}</strong><small>{{status.help}}</small></span><i class="bi check" :class="form.status===status.value?'bi-check-circle-fill':'bi-circle'"></i></button></div><em v-if="form.errors.status" class="error">{{form.errors.status}}</em></section>
  <footer><a :href="urls.index" class="btn btn-light">إلغاء</a><button class="btn btn-primary" :disabled="form.processing"><i class="bi bi-check2-circle"></i>{{form.processing?'جارٍ الحفظ…':editing?'حفظ التعديلات':'إضافة إلى الصالة'}}</button></footer>
</form>
</template>
<style scoped>
.table-form{max-width:920px;margin:auto;display:grid;gap:.85rem}.card{background:#fff;border:1px solid #dce7e0;border-radius:16px;padding:1rem;box-shadow:0 8px 24px rgba(20,67,42,.04)}.card header{display:flex;justify-content:space-between;align-items:center;padding-bottom:.85rem;border-bottom:1px solid #edf2ef;margin-bottom:.9rem}.card h2,.card small{margin:0}.card h2{font-size:1rem}.card header small{font-size:.7rem;color:#84938b}.preview-number{min-width:58px;height:58px;padding:.2rem .7rem;border-radius:16px;background:#e8f6ed;color:#0b7240;display:grid;place-items:center;font-size:1.5rem;font-weight:900}.fields{display:grid;grid-template-columns:repeat(2,1fr);gap:.8rem}.fields label{display:grid;gap:.35rem}.fields label>span{font-size:.76rem;font-weight:800}.fields label>small,.fields label>a{font-size:.67rem;color:#7d8c84}.fields label>a{color:#147344;text-decoration:none}.fields em,.error{color:#bd3434;font-size:.67rem;font-style:normal}.number{font-size:1.1rem;font-weight:900}.capacity{display:grid;grid-template-columns:42px 1fr 42px;border:1px solid #d9e4de;border-radius:10px;overflow:hidden}.capacity input{border:0;text-align:center;font-weight:900;min-width:0}.capacity button{border:0;background:#eff7f2;color:#0e7140;font-size:1.2rem}.status-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:.6rem}.status-grid button{display:grid;grid-template-columns:38px 1fr 20px;align-items:center;gap:.6rem;text-align:start;border:1px solid #dfe7e2;background:#fff;border-radius:12px;padding:.7rem}.status-grid button>i:first-child{width:38px;height:38px;display:grid;place-items:center;border-radius:10px;background:#f0f5f2;color:#557165}.status-grid button span{display:grid}.status-grid strong{font-size:.78rem}.status-grid small{font-size:.66rem;color:#809087}.status-grid .check{color:#9aaba2}.status-grid button.selected{border-color:#55a779;background:#f2faf5;box-shadow:0 0 0 2px rgba(30,130,75,.07)}.status-grid button.selected>i{color:#107140}.active-switch{display:flex;align-items:center;gap:.4rem;font-size:.73rem}.active-switch input{display:none}.active-switch span{width:42px;height:24px;background:#ccd7d1;border-radius:99px;position:relative}.active-switch span:after{content:'';position:absolute;width:18px;height:18px;top:3px;right:3px;border-radius:50%;background:#fff;transition:.2s}.active-switch input:checked+span{background:#16834a}.active-switch input:checked+span:after{transform:translateX(-18px)}footer{display:flex;justify-content:flex-end;gap:.55rem;padding:.2rem}footer .btn{min-width:150px;min-height:46px;font-weight:800}@media(max-width:620px){.fields,.status-grid{grid-template-columns:1fr}.card{border-radius:13px;padding:.85rem}.status-grid button{grid-template-columns:34px 1fr 18px}.status-grid button>i:first-child{width:34px;height:34px}footer{position:sticky;bottom:0;background:#f5f8f6;padding:.6rem;z-index:3}footer .btn{min-width:0;flex:1}}
</style>
