<script setup>
import { computed } from 'vue';
import { Head, useForm } from '@inertiajs/vue3';
import AdminLayout from '../../../Layouts/AdminLayout.vue';
import DataPanel from '../../../Components/Ui/DataPanel.vue';
import PageHeader from '../../../Components/Ui/PageHeader.vue';
defineOptions({layout:AdminLayout});
const props=defineProps({unit:{type:Object,required:true},types:{type:Array,required:true},urls:{type:Object,required:true}});
const editing=computed(()=>Boolean(props.unit.id));const form=useForm({code:props.unit.code,name:props.unit.name,unit_type:props.unit.type,factor_to_base:props.unit.factor,is_base:props.unit.base});
const selected=computed(()=>props.types.find(x=>x.value===form.unit_type));
function submit(){editing.value?form.put(props.urls.submit):form.post(props.urls.submit)}
</script>
<template>
<Head :title="editing?'تعديل وحدة':'وحدة جديدة'"/><PageHeader :title="editing?`تعديل ${unit.name}`:'وحدة قياس جديدة'" icon="bi-rulers" :subtitle="editing&&unit.used?'الوحدة مستخدمة؛ غيّر الاسم بحذر ولا تغيّر معناها أو معاملها.':'عرّف معنى الوحدة ومعاملها مرة واحدة'" :crumbs="[{label:'وحدات القياس',url:urls.index}]"/>
<div v-if="editing&&unit.used" class="warning"><i class="bi bi-exclamation-triangle-fill"></i><span><strong>هذه الوحدة مستخدمة في بيانات سابقة</strong><small>تغيير المعامل يغيّر معنى العرض في كل مكان. إن احتجت معنى جديداً، أنشئ وحدة جديدة.</small></span></div>
<form @submit.prevent="submit"><DataPanel title="تعريف الوحدة" icon="bi-sliders2"><div class="type-cards"><button v-for="type in types" :key="type.value" type="button" :class="{active:form.unit_type===type.value}" @click="form.unit_type=type.value"><i class="bi" :class="{weight:'bi-speedometer',volume:'bi-droplet-fill',count:'bi-123',length:'bi-rulers'}[type.value]"></i><span><strong>{{type.label}}</strong><small>أساسه المعتاد: {{type.baseExample}}</small></span><i class="bi" :class="form.unit_type===type.value?'bi-check-circle-fill':'bi-circle'"></i></button></div><div class="unit-fields"><label><span>الرمز *</span><input v-model="form.code" class="form-control" maxlength="16" required placeholder="kg"><small v-if="form.errors.code">{{form.errors.code}}</small></label><label><span>الاسم *</span><input v-model="form.name" class="form-control" required placeholder="كيلوغرام"></label><label><span>معامل التحويل *</span><input v-model="form.factor_to_base" type="number" step="0.0000001" min="0.0000001" class="form-control" required><small>{{selected?.example}}</small></label></div><button type="button" class="base-toggle" :class="{active:form.is_base}" @click="form.is_base=!form.is_base"><i class="bi" :class="form.is_base?'bi-check-circle-fill':'bi-circle'"></i><span><strong>وحدة أساسية لهذا النوع</strong><small>الوحدة الأساسية معاملها عادة 1، مثل غرام أو ملليلتر أو قطعة.</small></span></button></DataPanel><div class="save-bar"><a :href="urls.index" class="btn btn-light">إلغاء</a><span></span><button class="btn btn-primary" :disabled="form.processing"><i class="bi bi-check2"></i> حفظ الوحدة</button></div></form>
</template>
<style scoped>
.warning{display:flex;gap:10px;margin-bottom:10px;padding:12px 14px;border:1px solid #e2c17c;border-radius:13px;color:#8c5700;background:#fff7e8}.warning span{display:grid}.warning strong{font-size:.7rem}.warning small{font-size:.6rem}.type-cards{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-bottom:14px}.type-cards button{display:flex;align-items:center;gap:8px;padding:11px;border:1px solid #dfe7e2;border-radius:12px;color:#5b6a61;background:#fff;text-align:start}.type-cards button>i:first-child{display:grid;width:36px;height:36px;place-items:center;border-radius:9px;color:#176b39;background:#edf6ef}.type-cards span{display:grid;flex:1}.type-cards strong{font-size:.66rem}.type-cards small{color:#86928a;font-size:.54rem}.type-cards button>i:last-child{font-size:.7rem}.type-cards button.active{color:#176b39;border-color:#97c6a5;background:#f0f8f2}.unit-fields{display:grid;grid-template-columns:1fr 2fr 2fr 1.4fr;gap:10px}.unit-fields label{display:grid;gap:5px}.unit-fields label>span{font-size:.63rem;font-weight:850}.unit-fields label>small{color:#7f8c84;font-size:.56rem}.unit-fields label>small:not(:last-child){color:#b42318}.base-toggle{display:flex;width:100%;align-items:center;gap:9px;margin-top:12px;padding:11px;border:1px solid #dfe7e2;border-radius:12px;color:#66756c;background:#fafbfa;text-align:start}.base-toggle span{display:grid}.base-toggle strong{font-size:.67rem}.base-toggle small{color:#849188;font-size:.56rem}.base-toggle.active{color:#176b39;border-color:#9cc9a9;background:#eff8f2}.save-bar{position:sticky;bottom:8px;z-index:8;display:flex;gap:8px;margin-top:10px;padding:11px;border:1px solid #cbded1;border-radius:14px;background:rgba(255,255,255,.97);box-shadow:0 12px 35px rgba(20,50,31,.12)}.save-bar span{flex:1}
@media(max-width:800px){.type-cards{grid-template-columns:1fr 1fr}.unit-fields{grid-template-columns:1fr 1fr}}
@media(max-width:500px){.type-cards,.unit-fields{grid-template-columns:1fr}.save-bar .btn-primary{flex:1}}
</style>
