<script setup>
import { Head } from '@inertiajs/vue3';
import AdminLayout from '../../../Layouts/AdminLayout.vue';
import DataPanel from '../../../Components/Ui/DataPanel.vue';
import EmptyState from '../../../Components/Ui/EmptyState.vue';
import PageHeader from '../../../Components/Ui/PageHeader.vue';
import StatRail from '../../../Components/Ui/StatRail.vue';
defineOptions({layout:AdminLayout});
defineProps({supplier:{type:Object,required:true},totals:{type:Object,required:true},ingredients:{type:Array,default:()=>[]},scopeLabel:{type:String,default:'كل الفروع'},can:{type:Object,required:true},urls:{type:Object,required:true}});
</script>
<template>
<Head :title="supplier.name"/>
<PageHeader :title="supplier.name" icon="bi-truck" subtitle="ملف المورّد والتوريد والرصيد المخزني المرتبط به" :crumbs="[{label:'الموردون',url:urls.index}]">
 <template #actions><a v-if="can.update" :href="urls.edit" class="btn btn-light"><i class="bi bi-pencil"></i> تعديل</a><a :href="urls.newPurchaseOrder" class="btn btn-primary"><i class="bi bi-plus-lg"></i> أمر شراء</a></template>
</PageHeader>
<StatRail :stats="[{label:'المكونات',value:totals.ingredientCount,icon:'bi-boxes',color:'primary'},{label:'مخزون منخفض',value:totals.lowStock,icon:'bi-exclamation-triangle',color:'danger'},{label:'قيمة المخزون المرتبط',value:totals.stockValue,icon:'bi-cash-coin',color:'accent'},{label:'الحالة',value:supplier.active?'فعّال':'متوقف',icon:supplier.active?'bi-check-circle-fill':'bi-pause-circle',color:supplier.active?'success':'muted'}]"/>
<div class="supplier-layout">
 <aside>
  <DataPanel title="بيانات التواصل" icon="bi-person-vcard"><div class="facts"><div v-if="supplier.contactPerson"><i class="bi bi-person"></i><span><small>المسؤول</small><b>{{supplier.contactPerson}}</b></span></div><div v-if="supplier.phone"><i class="bi bi-telephone"></i><span><small>الهاتف</small><a :href="`tel:${supplier.phone}`">{{supplier.phone}}</a></span></div><div v-if="supplier.email"><i class="bi bi-envelope"></i><span><small>البريد</small><a :href="`mailto:${supplier.email}`">{{supplier.email}}</a></span></div><div v-if="supplier.address"><i class="bi bi-geo-alt"></i><span><small>العنوان</small><b>{{supplier.address}}</b></span></div><div v-if="supplier.notes"><i class="bi bi-journal-text"></i><span><small>ملاحظات</small><b>{{supplier.notes}}</b></span></div><EmptyState v-if="!supplier.contactPerson&&!supplier.phone&&!supplier.email&&!supplier.address&&!supplier.notes" compact icon="bi-person-vcard" message="لا توجد بيانات تواصل"/></div></DataPanel>
  <DataPanel title="اتفاق التوريد" icon="bi-calendar2-week"><div class="terms"><span><small>مهلة التوريد</small><b>{{supplier.leadTimeDays===null?'غير محددة':`${supplier.leadTimeDays} يوم`}}</b></span><span><small>مهلة الدفع</small><b>{{supplier.paymentTermsDays===null?'غير محددة':supplier.paymentTermsDays===0?'فوري':`${supplier.paymentTermsDays} يوم`}}</b></span><span><small>أقل طلب</small><b>{{supplier.minimumOrderAmount??'لا يوجد'}}</b></span><div v-if="supplier.branches?.length"><small>الفروع التي يورّد لها</small><p><b v-for="branch in supplier.branches" :key="branch.id">{{branch.name}}</b></p></div><div v-if="supplier.deliveryDays.length"><small>أيام التوصيل</small><p><b v-for="day in supplier.deliveryDays" :key="day">{{day}}</b></p></div></div></DataPanel>
  <div class="quick-links"><a :href="urls.purchaseOrders"><i class="bi bi-bag-check"></i><span>أوامر الشراء</span><i class="bi bi-chevron-left"></i></a><a :href="urls.invoices"><i class="bi bi-receipt"></i><span>فواتير المورد</span><i class="bi bi-chevron-left"></i></a><a :href="urls.prices"><i class="bi bi-graph-up-arrow"></i><span>تاريخ الأسعار</span><i class="bi bi-chevron-left"></i></a><a :href="urls.compare"><i class="bi bi-arrows-collapse"></i><span>قارن الموردين</span><i class="bi bi-chevron-left"></i></a></div>
 </aside>
 <DataPanel :title="`المكونات المرتبطة · ${scopeLabel}`" :count="ingredients.length" icon="bi-boxes">
  <div v-if="ingredients.length" class="ingredient-list"><a v-for="item in ingredients" :key="item.id" :href="item.url" :class="{low:item.lowStock}"><div><strong>{{item.name}}</strong><small><code>{{item.sku}}</code><span v-if="item.lowStock">يحتاج توريد</span></small></div><span><small>المتوفر</small><b>{{item.stock}}</b></span><span><small>حد الطلب</small><b>{{item.reorder}}</b></span><span><small>تكلفة الوحدة</small><b>{{item.unitCost}}</b></span><span><small>القيمة</small><b>{{item.stockValue}}</b></span><i class="bi bi-chevron-left"></i></a></div>
  <EmptyState v-else icon="bi-boxes" title="لا توجد مكونات مرتبطة" message="اربط المكوّن بالمورد من ملف المكوّن."><template #cta><a :href="urls.ingredients" class="btn btn-primary">إدارة المكونات</a></template></EmptyState>
 </DataPanel>
</div>
</template>
<style scoped>
.supplier-layout{display:grid;grid-template-columns:330px minmax(0,1fr);align-items:start;gap:12px}.supplier-layout aside{display:grid;gap:10px}.facts{display:grid;padding:4px}.facts>div{display:flex;gap:10px;padding:10px;border-bottom:1px solid #edf1ee}.facts>div>i{display:grid;width:34px;height:34px;place-items:center;border-radius:9px;color:#176b39;background:#eaf5ed}.facts span{display:grid;min-width:0}.facts small,.terms small,.ingredient-list small{color:#819087;font-size:.57rem}.facts b,.facts a{color:#33453a;font-size:.68rem;word-break:break-word}.terms{display:grid;grid-template-columns:1fr 1fr;gap:8px;padding:4px}.terms>span,.terms>div{display:grid;padding:10px;border-radius:10px;background:#f5f8f6}.terms b{font-size:.68rem}.terms>div{grid-column:1/-1}.terms p{display:flex;flex-wrap:wrap;gap:4px;margin:5px 0 0}.terms p b{padding:3px 6px;border-radius:7px;color:#176b39;background:#e6f3ea;font-size:.56rem}.quick-links{display:grid;grid-template-columns:1fr 1fr;gap:6px}.quick-links a{display:flex;align-items:center;gap:7px;min-height:42px;padding:9px;border:1px solid #dfe7e2;border-radius:11px;color:#526158;background:#fff}.quick-links span{flex:1;font-size:.62rem;font-weight:800}.quick-links i:last-child{font-size:.55rem}.ingredient-list{display:grid;gap:6px}.ingredient-list>a{display:grid;grid-template-columns:minmax(170px,1.4fr) repeat(4,minmax(90px,.7fr)) 16px;align-items:center;gap:9px;padding:11px;border:1px solid #e1e8e3;border-radius:12px;color:#34463b;background:#fff}.ingredient-list>a.low{border-inline-start:4px solid #dc8a13;background:#fffaf1}.ingredient-list>a>div,.ingredient-list>a>span{display:grid}.ingredient-list strong{font-size:.72rem}.ingredient-list code{margin-inline-end:6px}.ingredient-list div small span{padding:2px 5px;border-radius:99px;color:#9b5b00;background:#ffedc8}.ingredient-list b{font-size:.63rem}
@media(max-width:1050px){.supplier-layout{grid-template-columns:1fr}.supplier-layout aside{grid-template-columns:1fr 1fr}.quick-links{grid-column:1/-1;grid-template-columns:repeat(4,1fr)}.ingredient-list>a{grid-template-columns:minmax(150px,1.3fr) repeat(2,1fr) 16px}.ingredient-list>a>span:nth-of-type(3),.ingredient-list>a>span:nth-of-type(4){display:none}}
@media(max-width:650px){.supplier-layout aside{grid-template-columns:1fr}.quick-links{grid-column:auto;grid-template-columns:1fr 1fr}.ingredient-list>a{grid-template-columns:1fr 1fr 14px}.ingredient-list>a>div{grid-column:1/-2}.ingredient-list>a>span:nth-of-type(n+3){display:none}}
</style>
