<script setup>
import { Head } from '@inertiajs/vue3';
import AdminLayout from '../../../Layouts/AdminLayout.vue';
import PageHeader from '../../../Components/Ui/PageHeader.vue';
import EmptyState from '../../../Components/Ui/EmptyState.vue';
defineOptions({layout:AdminLayout});
defineProps({closure:{type:Object,required:true},sheet:{type:Array,default:()=>[]},overflowTotal:String,urls:{type:Object,required:true}});
const printSheet=()=>window.print();
</script>
<template>
<Head :title="`كشف بدل الوجبات ${closure.monthValue}`"/>
<div class="closure-page"><PageHeader :title="`كشف بدل الوجبات · ${closure.month}`" icon="bi-printer-fill" subtitle="كشف التسوية النهائي للمحاسبة والرواتب" :crumbs="[{label:'بدل الوجبات',url:urls.index},{label:'الإقفالات',url:urls.closures}]"><template #actions><button class="btn btn-primary" type="button" @click="printSheet"><i class="bi bi-printer"></i> طباعة الكشف</button></template></PageHeader>
<section class="document-head"><div class="brand-mark"><i class="bi bi-cup-hot-fill"></i></div><div><small>كشف تسوية بدل وجبات الموظفين</small><h1>{{closure.month}}</h1><p>{{closure.branch}}</p></div><span class="final"><i class="bi bi-shield-check"></i> كشف مقفل</span></section>
<section class="meta"><div><small>طريقة التسوية</small><strong>{{closure.method}}</strong></div><div><small>عدد الموظفين</small><strong>{{closure.staffCount}}</strong></div><div><small>عدد الحركات</small><strong>{{closure.chargeCount}}</strong></div><div class="grand"><small>إجمالي التسوية</small><strong>{{closure.total}}</strong></div></section>
<section v-if="closure.notes" class="notes"><i class="bi bi-sticky-fill"></i><div><small>ملاحظة الإقفال</small><p>{{closure.notes}}</p></div></section>
<section class="sheet"><header><div><small>تفصيل الموظفين</small><h2>بنود الكشف</h2></div><span>{{sheet.length}} موظفاً</span></header><div v-if="sheet.length" class="table-wrap"><table><thead><tr><th>#</th><th>الموظف</th><th>الدور</th><th>البدل الشهري</th><th>المخصوم</th><th>التجاوز</th><th>الحركات</th><th class="signature">التوقيع</th></tr></thead><tbody><tr v-for="(row,index) in sheet" :key="index"><td>{{index+1}}</td><td><strong>{{row.name}}</strong></td><td>{{row.role}}</td><td>{{row.allowance}}</td><td class="amount">{{row.total}}</td><td :class="{over:row.overflow>0}">{{row.overflow>0?`+ ${row.overflowFormatted}`:'—'}}</td><td>{{row.chargesCount}}</td><td class="signature"></td></tr></tbody><tfoot><tr><td colspan="4">الإجمالي</td><td>{{closure.total}}</td><td>{{overflowTotal}}</td><td>{{closure.chargeCount}}</td><td class="signature"></td></tr></tfoot></table></div><EmptyState v-else icon="bi-inbox" title="الكشف فارغ" message="لم تُربط حركات بهذا الإقفال."/></section>
<footer class="document-footer"><p>أُقفل بواسطة <strong>{{closure.closedBy}}</strong> بتاريخ <bdi>{{closure.closedAt}}</bdi>.</p><div class="signatures"><span><i></i><b>الموارد البشرية</b></span><span><i></i><b>المحاسبة</b></span><span><i></i><b>المدير العام</b></span></div></footer></div>
</template>
<style>
.closure-page{max-width:1180px;margin:auto}.document-head,.meta,.sheet,.notes{background:#fff;border:1px solid #dce6e0;border-radius:15px}.document-head{display:flex;align-items:center;gap:.8rem;padding:1rem;margin-bottom:.7rem}.brand-mark{width:50px;height:50px;border-radius:15px;background:#e7f4ec;color:#107140;display:grid;place-items:center;font-size:1.25rem}.document-head small{font-size:.65rem;color:#819087}.document-head h1{font-size:1.15rem;margin:.1rem 0}.document-head p{font-size:.7rem;color:#5f7167;margin:0}.final{margin-inline-start:auto;padding:.4rem .65rem;border-radius:99px;background:#eaf6ee;color:#107140;font-size:.66rem;font-weight:800}.meta{display:grid;grid-template-columns:repeat(4,1fr);margin-bottom:.7rem;overflow:hidden}.meta>div{display:grid;padding:.75rem 1rem;border-inline-end:1px solid #e9efeb}.meta small{font-size:.62rem;color:#819087}.meta strong{font-size:.78rem}.meta .grand{background:#f0f8f3}.meta .grand strong{color:#0d713f;font-size:.95rem}.notes{display:flex;gap:.6rem;padding:.7rem 1rem;margin-bottom:.7rem;color:#63776b}.notes small{font-size:.62rem;color:#819087}.notes p{font-size:.69rem;margin:.12rem 0}.sheet{overflow:hidden}.sheet>header{display:flex;justify-content:space-between;padding:.85rem 1rem;border-bottom:1px solid #e9efeb}.sheet h2,.sheet small{margin:0}.sheet h2{font-size:.9rem}.sheet header small{font-size:.62rem;color:#819087}.sheet header>span{font-size:.64rem;color:#60746a}.table-wrap{overflow-x:auto}.sheet table{width:100%;border-collapse:collapse}.sheet th,.sheet td{padding:.7rem .75rem;text-align:start;border-bottom:1px solid #e9efeb;font-size:.68rem}.sheet th{background:#f5f8f6;color:#5f7267;font-size:.63rem}.sheet td.amount{color:#0e713f;font-weight:850}.sheet td.over{color:#b63939;font-weight:850}.sheet tfoot td{background:#f2f7f4;font-weight:850}.signature{display:none}.document-footer{padding:1rem}.document-footer>p{text-align:center;color:#75857c;font-size:.65rem}.signatures{display:none}.signatures span{flex:1;text-align:center}.signatures i{display:block;border-top:1px solid #444;margin-bottom:.4rem}.signatures b{font-size:.7rem}@media(max-width:650px){.meta{grid-template-columns:1fr 1fr}.document-head{border-radius:13px}.final{font-size:0}.final i{font-size:.8rem}.sheet th,.sheet td{white-space:nowrap;padding:.6rem}.document-head h1{font-size:1rem}}@media print{.app-header,.app-sidebar,.footer,.closure-page .page-header,.rq-toast-stack,.rq-confirm-backdrop{display:none!important}.main-content.app-content{padding:0!important;margin:0!important}.main-content .container-fluid{max-width:none!important;padding:0!important}.closure-page{max-width:none;color:#000}.document-head,.meta,.sheet,.notes{box-shadow:none;border-color:#777;border-radius:0}.signature{display:table-cell!important;min-width:120px}.document-footer{break-inside:avoid}.signatures{display:flex;gap:2rem;margin-top:3rem}.sheet th,.sheet td{font-size:10px}.sheet tr{break-inside:avoid}.document-head{margin-top:0}}
</style>
