<script setup>
import { Head } from '@inertiajs/vue3';
import AdminLayout from '../../../Layouts/AdminLayout.vue';
import PageHeader from '../../../Components/Ui/PageHeader.vue';
import Pagination from '../../../Components/Ui/Pagination.vue';
import EmptyState from '../../../Components/Ui/EmptyState.vue';
defineOptions({layout:AdminLayout});
defineProps({closures:{type:Object,required:true},urls:{type:Object,required:true}});
const methodIcon={payroll_deduction:'bi-person-vcard',cash:'bi-cash-stack',writeoff:'bi-eraser-fill'};
</script>
<template>
<Head title="إقفالات بدل الوجبات"/>
<PageHeader title="إقفالات بدل الوجبات" icon="bi-archive-fill" subtitle="كشوف ثابتة للمحاسبة والرواتب يمكن الرجوع إليها وطباعتها" :crumbs="[{label:'بدل الوجبات',url:urls.index}]"/>
<section class="closures-panel"><header><div><small>السجل الشهري</small><h2>{{closures.total}} إقفالاً</h2></div><span><i class="bi bi-shield-check"></i> لا يتغير الكشف بعد الإقفال</span></header><div v-if="closures.data.length" class="closure-list"><article v-for="closure in closures.data" :key="closure.id"><div class="month"><i class="bi bi-calendar2-check"></i><span><small>الشهر</small><strong>{{closure.month}}</strong></span></div><div class="branch"><small>الفرع</small><strong>{{closure.branch}}</strong></div><div class="method"><i class="bi" :class="methodIcon[closure.method]||'bi-check2-circle'"></i><span><small>طريقة التسوية</small><strong>{{closure.methodLabel}}</strong></span></div><div class="counts"><span><small>الموظفون</small><b>{{closure.staffCount}}</b></span><span><small>الحركات</small><b>{{closure.chargeCount}}</b></span></div><div class="total"><small>إجمالي الكشف</small><strong>{{closure.total}}</strong><em>{{closure.closedAt}} · {{closure.closedBy}}</em></div><a :href="closure.showUrl"><span>فتح الكشف</span><i class="bi bi-printer"></i></a></article></div><EmptyState v-else icon="bi-archive" title="لا توجد إقفالات بعد" message="ارجع لبدل الوجبات واختر «إقفال الشهر» بعد مراجعة الحركات."/><footer><Pagination :links="closures.links"/></footer></section>
</template>
<style scoped>
.closures-panel{background:#fff;border:1px solid #dce6e0;border-radius:16px;overflow:hidden;box-shadow:0 8px 28px rgba(20,62,40,.045)}.closures-panel>header{display:flex;justify-content:space-between;align-items:center;padding:1rem;border-bottom:1px solid #e9efeb}.closures-panel h2,.closures-panel small{margin:0}.closures-panel h2{font-size:1rem}.closures-panel header small{font-size:.65rem;color:#819087}.closures-panel>header>span{display:flex;align-items:center;gap:.35rem;padding:.4rem .6rem;border-radius:9px;background:#f0f7f3;color:#107140;font-size:.65rem}.closure-list article{display:grid;grid-template-columns:130px minmax(140px,.75fr) minmax(160px,.85fr) 140px minmax(180px,1fr) 110px;gap:.75rem;align-items:center;padding:.8rem 1rem;border-bottom:1px solid #edf1ef}.month,.method{display:flex;align-items:center;gap:.5rem}.month>i,.method>i{width:36px;height:36px;border-radius:10px;background:#eaf5ee;color:#117140;display:grid;place-items:center}.month span,.method span,.branch,.total{display:grid}.closure-list small{font-size:.6rem;color:#819087}.closure-list strong{font-size:.7rem}.counts{display:flex;gap:.8rem}.counts span{display:grid}.counts b{font-size:.8rem}.total strong{color:#107140;font-size:.78rem}.total em{font-size:.58rem;color:#87948d;font-style:normal}.closure-list article>a{display:flex;justify-content:space-between;align-items:center;padding:.5rem .6rem;border-radius:9px;background:#eff7f2;color:#107140;text-decoration:none;font-size:.65rem;font-weight:800}.closures-panel>footer{padding:.8rem}@media(max-width:1000px){.closure-list article{grid-template-columns:120px 1fr 1fr 100px}.counts{display:none}.total{grid-column:2/4}.closure-list article>a{grid-column:4;grid-row:1/3}}@media(max-width:620px){.closure-list article{grid-template-columns:1fr auto;padding:.75rem}.branch,.method{grid-column:1}.total{grid-column:1}.closure-list article>a{grid-column:2;grid-row:1/5}.closure-list article>a span{display:none}.closures-panel{border-radius:13px}.closures-panel>header>span{display:none}}
</style>
