<script setup>
import { computed } from 'vue';
import { Head, useForm } from '@inertiajs/vue3';
import AdminLayout from '../../../Layouts/AdminLayout.vue';
import PageHeader from '../../../Components/Ui/PageHeader.vue';
import EmptyState from '../../../Components/Ui/EmptyState.vue';

defineOptions({ layout: AdminLayout });
const props = defineProps({ states:Array, role:String, enabled:Boolean, cloudUrl:String, urls:Object });
const form = useForm({});
const roleMeta = computed(() => ({branch:{label:'جهاز فرع',hint:'يرفع التغييرات إلى السحابة'},cloud:{label:'الخادم السحابي',hint:'يستقبل بيانات الفروع'},standalone:{label:'جهاز مستقل',hint:'المزامنة غير مستخدمة'}}[props.role]||{label:'جهاز مستقل',hint:'المزامنة غير مستخدمة'}));
const labels={ok:'ناجحة',offline:'غير متصل',error:'خطأ',pending:'بانتظار أول تشغيل'};
function run(){form.post(props.urls.run,{preserveScroll:true});}
</script>
<template>
<Head title="حالة المزامنة" />
<PageHeader title="حالة المزامنة" icon="bi-cloud-arrow-up-fill" subtitle="شاشة تشخيص تقنية؛ التشغيل اليومي لا يعتمد على فتحها"><template #actions><button v-if="enabled" type="button" class="btn btn-primary" :disabled="form.processing" @click="run"><i class="bi bi-arrow-repeat"></i> مزامنة الآن</button></template></PageHeader>
<section class="device" :class="{disabled:!enabled}"><span><i class="bi" :class="enabled?'bi-cloud-check-fill':'bi-cloud-slash-fill'"></i></span><div><small>هذا الجهاز</small><h2>{{roleMeta.label}}</h2><p>{{roleMeta.hint}}</p></div><dl><div><dt>الحالة</dt><dd>{{enabled?'مفعّلة':'متوقفة'}}</dd></div><div><dt>عنوان السحابة</dt><dd>{{cloudUrl||'—'}}</dd></div></dl></section>
<section class="streams"><header><div><small>تفاصيل تقنية</small><h2>مسارات البيانات</h2></div><span>{{states.length}} مسار</span></header><div v-if="states.length" class="stream-list"><article v-for="state in states" :key="state.id" :data-status="state.status"><i class="bi direction" :class="state.direction==='down'?'bi-cloud-arrow-down-fill':'bi-cloud-arrow-up-fill'"></i><div><strong>{{state.stream}}</strong><small>{{state.direction==='down'?'تنزيل إلى هذا الجهاز':'رفع إلى السحابة'}}</small></div><span class="status"><i class="bi" :class="state.status==='ok'?'bi-check-circle-fill':state.status==='error'?'bi-x-octagon-fill':state.status==='offline'?'bi-wifi-off':'bi-clock-fill'"></i>{{labels[state.status]||labels.pending}}</span><b>{{state.count||0}} صف</b><time>{{state.lastSyncedAt||'لم تتم بعد'}}</time><p v-if="state.error">{{state.error}}</p></article></div><EmptyState v-else icon="bi-cloud-slash" title="لم تتم أي مزامنة بعد" :message="enabled?'سيظهر السجل بعد أول تشغيل تلقائي أو يدوي.':'المزامنة متوقفة على هذا الجهاز، وهذا طبيعي في وضع الاستضافة الواحدة.'" /></section>
</template>
<style scoped>
.device,.streams{background:#fff;border:1px solid #dce6e0;border-radius:16px;margin-top:.8rem}.device{display:grid;grid-template-columns:48px 1fr minmax(300px,.9fr);gap:.75rem;align-items:center;padding:1rem}.device>span{display:grid;place-items:center;width:46px;height:46px;border-radius:12px;background:#e9f7ef;color:#0c7742;font-size:1.2rem}.device.disabled>span{background:#f0f2f1;color:#718078}.device h2{font-size:.95rem;margin:.05rem 0}.device small,.device p{font-size:.62rem;color:#788880;margin:0}.device dl{display:grid;grid-template-columns:1fr 2fr;margin:0;background:#f5f8f6;border-radius:11px}.device dl div{padding:.55rem .7rem;min-width:0}.device dt{font-size:.59rem;color:#7a8a81}.device dd{font-size:.68rem;font-weight:800;margin:0;overflow:hidden;text-overflow:ellipsis}.streams{overflow:hidden}.streams>header{display:flex;justify-content:space-between;align-items:center;padding:1rem;border-bottom:1px solid #e8eeea}.streams h2{font-size:1rem;margin:.05rem 0}.streams header small{font-size:.62rem;color:#7a8a81}.streams header>span{font-size:.64rem;background:#edf5f0;color:#137442;padding:.3rem .55rem;border-radius:99px}.stream-list article{display:grid;grid-template-columns:42px minmax(150px,1fr) 130px 75px 110px;gap:.65rem;align-items:center;padding:.7rem 1rem;border-bottom:1px solid #edf1ef}.direction{display:grid;place-items:center;width:38px;height:38px;border-radius:10px;background:#edf6f1;color:#117542}.stream-list article>div{display:grid}.stream-list strong{font-size:.73rem}.stream-list small,.stream-list time{font-size:.6rem;color:#7b8982}.status{display:flex;align-items:center;gap:.3rem;font-size:.64rem;color:#9d6809}.stream-list article[data-status=ok] .status{color:#0b7742}.stream-list article[data-status=error] .status{color:#b33838}.stream-list b{font-size:.66rem}.stream-list p{grid-column:2/-1;margin:0;background:#fff0f0;color:#a73838;padding:.4rem;border-radius:8px;font-size:.6rem;text-align:left}@media(max-width:720px){.device{grid-template-columns:46px 1fr}.device dl{grid-column:1/-1}.stream-list article{grid-template-columns:38px 1fr auto}.stream-list b{grid-column:2}.stream-list time{grid-column:3}.stream-list .status{grid-column:3;grid-row:1/2}.stream-list p{grid-column:1/-1}}
</style>
